name: Update VPNGate CSV

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download VPNGate CSV
        run: |
          curl -L https://www.vpngate.net/api/iphone/ -o vpngate.csv

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Commit and Push
        run: |
          git add vpngate.csv
          git commit -m "Auto update VPNGate CSV" || echo "No changes to commit"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}